#!/usr/bin/env python
# encoding: utf-8
"""
@Author: Lekwe
@License: (C) Copyright 2013-2021, Lekwe Armat co.,ltd
@Contact: zscleo@qq.com leokeyn@sina.cn
@Software: Pycharm
@File: Main.py
@Time: 2021/2/8 15:38
@Desc:
"""
from requests import *
from bs4 import BeautifulSoup
import os
import lxml
import winreg
from colorama import Fore, Back, init

init(autoreset=True)

while True:
    def isConnected(url):
        try:
            test = get(url=url, timeout=2)
            return True
        except:
            return False


    returns = isConnected("http://180.97.33.108/")
    if returns:
        while True:
            print(Fore.CYAN + "请输入歌曲id或歌曲链接(酷我):", end='')
            songinfo = str(input(" "))
            songid = songinfo.replace('http://www.kuwo.cn/play_detail/', '').replace('https://www.kuwo.cn/play_detail/','').replace('www.kuwo.cn/play_detail/', '').replace('http://kuwo.cn/play_detail/', '').replace('https://kuwo.cn/play_detail/', '').replace('kuwo.cn/play_detail/', '')
            url = "http://www.kuwo.cn/url?format=mp3&rid={}&response=url&type=convert_url3&br=128kmp3&from=web&t=1612769264838&httpsStatus=1&reqId=22dbdd71-69df-11eb-be09-47f3f4fea7e7".format(songid)
            headers = {
                "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                "Accept-Encoding": "gzip, deflate",
                "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "Cookie": "Hm_lvt_cdb524f42f0ce19b169a8071123a4797=1612769220; _ga=GA1.2.1755212516.1612769220; _gid=GA1.2.641293631.1612769220; kw_token=KFFFC3SKZ8",
                "Host": "www.kuwo.cn",
                "Pragma": "no-cache",
                "Upgrade-Insecure-Requests": "1"
            }

            try:
                req = get(url=url, headers=headers).text
                pe1 = req.replace('{"code": 200, "msg": "success", "url": "', "")
                songurl = pe1.replace('"}', "")
                res = get("http://www.kuwo.cn/play_detail/" + songid)
                res.encoding = 'utf-8'  #
                soup = BeautifulSoup(res.text, 'lxml')
                song = soup.title.text
                name = str(song).replace('_单曲在线试听_酷我音乐', '').replace('_', '-')
                f1 = "?"
                f2 = "<"
                f3 = ">"
                f4 = ":"
                f5 = "/"
                f6 = '\\'
                f7 = "|"
                f8 = "*"
                f9 = '"'
                names = list(name)
                try:
                    i = names.index(f1)
                    names.pop(i)
                    names.insert(i, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“?”,已更换为-")
                except:
                    pass
                try:
                    i2 = names.index(f2)
                    names.pop(i2)
                    names.insert(i2, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“<”,已更换为-")
                except:
                    pass
                try:
                    i3 = names.index(f3)
                    names.pop(i3)
                    names.insert(i3, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“>”,已更换为-")
                except:
                    pass
                try:
                    i4 = names.index(f4)
                    names.pop(i4)
                    names.insert(i4, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“:”,已更换为-")
                except:
                    pass
                try:
                    i5 = names.index(f5)
                    names.pop(i5)
                    names.insert(i5, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“/”,已更换为-")
                except:
                    pass
                try:
                    i6 = names.index(f6)
                    names.pop(i6)
                    names.insert(i6, '-')
                    print(Fore.YELLOW + r"歌曲名中含有特殊符号“\”,已更换为-")
                except:
                    pass
                try:
                    i7 = names.index(f7)
                    names.pop(i7)
                    names.insert(i7, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“|”,已更换为-")
                except:
                    pass
                try:
                    i8 = names.index(f8)
                    names.pop(i8)
                    names.insert(i8, '-')
                    print(Fore.YELLOW + "歌曲名中含有特殊符号“*”,已更换为-")
                except:
                    pass
                try:
                    i9 = names.index(f9)
                    names.pop(i9)
                    names.insert(i9, '-')
                    print(Fore.YELLOW + '歌曲名中含有特殊符号“"”,已更换为-')
                except:
                    pass
                name2 = "".join(names)
                if name2 == "服务错误":
                    print(Fore.BLACK + Back.RED + "酷我音乐服务器服务错误或你的链接、id错误，无法下载。请检查你的链接、id或稍后重试")
                    print(server-error)
                if songurl == "failed":
                    print(Fore.BLACK + Back.RED + "你输入的链接或id有误，请检查你的链接或id")
                    pass
                rp = get(url=songurl)
                key = winreg.OpenKey(winreg.HKEY_CURRENT_USER,
                                     r'Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders')
                wd = winreg.QueryValueEx(key, "Desktop")[0]
                path = wd
                if not os.path.exists(path + "\\music\\"):
                    os.mkdir(path + "\\music")

                filepath = path + "\\music\\" + "{}.mp3".format(name2)
                if os.path.exists(filepath):
                    print(Fore.YELLOW + Back.BLACK + "文件存在,已覆盖")
                    with open(filepath, 'wb') as f:
                        f.write(rp.content)
                else:
                    with open(filepath, 'wb') as f:
                        f.write(rp.content)
                print(Fore.GREEN + Back.BLACK + "下载成功,已存储到{}".format(filepath))
            except Exception as ex:
                def isConnected(url):
                    try:
                        test = get(url=url, timeout=2)
                        return True
                    except:
                        return False
                returns = isConnected("http://180.97.33.108/")
                if returns:
                    print(
                        Fore.BLUE + Back.BLACK + "爬取失败，请检查你的链接或id、网络设置，或代理设置，若都设置正常，请稍后再试，或向我们反馈下方" + Fore.YELLOW + "黄色" + Fore.BLUE + "英文错误信息:\n总工:张书畅\n邮箱:zscleo@qq.com\n    "
                                                 " abc.lkw@aliyun.com\nQQ:1144757260\n电话:18953021320\n副总工:赵子汉\n邮箱:a_1666666@126.com\n   "
                                                 "  a_1666666@yeah.net\nQQ:3199398113\n电话:13256210166")
                    print(Fore.YELLOW + str(ex))
                else:
                    print(Back.RED + Fore.BLACK + "你的网络未连接，请检查你的网络连接。")
                    print(
                        Fore.BLUE + Back.BLACK + "爬取失败，请检查你的链接或id、网络设置，或代理设置，若都设置正常，请稍后再试，或向我们反馈下方" + Fore.YELLOW + "黄色" + Fore.BLUE + "英文错误信息:\n总工:张书畅\n邮箱:zscleo@qq.com\n    "
                                                 " abc.lkw@aliyun.com\nQQ:1144757260\n电话:18953021320\n副总工:赵子汉\n邮箱:a_1666666@126.com\n   "
                                                 "  a_1666666@yeah.net\nQQ:3199398113\n电话:13256210166")
                    print(Fore.YELLOW + str(ex))
    else:
        print(Fore.YELLOW + "你的网络未连接，请检查你的网络连接,设置好后按下回车键继续")
        input()
